### ISSUE TITLE
Why Void instead of a new VoidType?

### ISSUE THREAD

**Issue by seebacherd** [imglib/imglib2-roi#20]
Why is a LabelRegion an IterableInterval of type ```java.lang.Void``` instead of a new empty ```VoidType```? Now every implementation which is uses IterableInterval<T extends Type<T>> etc. is broken.

**Comment by tpietzsch** [comment]
@seebacherd I don't understand. What is broken now? What would cahnge if we used VoidType instead?

**Comment by dietzc** [comment]
@seebacherd as already mentoined in skype: Can you name a few scenarios where the `Type` property is required by your implementation which can also be used without the property (because `VoidType` has no property at all and https://github.com/imglib/imglib2/blob/master/src/main/java/net/imglib2/IterableInterval.java is not typed on `Type`?

**Comment by dietzc** [comment]
I think this can be closed

**Comment by tpietzsch** [comment]
thanks @dietzc
